# Generated by Django 5.0.3 on 2024-04-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('type_account', models.CharField(choices=[('ahorro', 'Ahorro'), ('nomina', 'Nómina'), ('efectivo', 'Efectivo'), ('inversion', 'Inversión'), ('credito', 'Crédito'), ('wallet', 'Wallet'), ('departamental', 'Departamental'), ('vales', 'Vales')], max_length=50, verbose_name='Tipo de cuenta')),
                ('public_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Cuenta pública')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número')),
                ('cvv', models.CharField(blank=True, max_length=3, verbose_name='CVV')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Saldo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de corte')),
                ('is_active', models.BooleanField(default=False)),
                ('status_delete', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
