# Generated by Django 5.0.3 on 2024-04-08 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#FF6900', 'Naranja'), ('#FCB900', 'Amarillo'), ('#7BDCB5', 'Turquesa'), ('#00D084', 'Verde'), ('#8ED1FC', 'Azul cielo'), ('#0693E3', 'Azul'), ('#ABB8C3', 'Verde limón'), ('#EB144C', 'Rosa mexicano'), ('#F78DA7', 'Rosa claro'), ('#9900EF', 'Morado')], default='#E9E9E9', max_length=30, verbose_name='Color')),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion del concepto')),
                ('type_movement', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('type_clasification', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], max_length=10, verbose_name='Tipo de clasificación')),
                ('status_delete', models.BooleanField(default=False)),
                ('color', models.ManyToManyField(default=1, to='transactions.color')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'concepts',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del movimiento')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripcion del movimiento')),
                ('day', models.DateField(verbose_name='Dia del movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Importe del movimiento')),
                ('picture', models.ImageField(default='image.jpg', upload_to='movimientos')),
                ('status_delete', models.BooleanField(default=False)),
                ('account', models.ManyToManyField(to='accounts.account')),
                ('concept', models.ManyToManyField(to='transactions.concept')),
            ],
            options={
                'db_table': 'moves',
            },
        ),
    ]
